In [15]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
a=[10,0,30,40,50]
pd.Series(a)

0    10
1     0
2    30
3    40
4    50
dtype: int64

In [4]:
a=[3.5,4.5,3.0,4.5,6.5]
pd.Series(a)

0    3.5
1    4.5
2    3.0
3    4.5
4    6.5
dtype: float64

In [5]:
a=["lohith","hemanth","krishna","teja"]
pd.Series(a)

0     lohith
1    hemanth
2    krishna
3       teja
dtype: str

In [6]:
a=[5+7j,2+6j,3+8j]
pd.Series(a)

0    5.0+7.0j
1    2.0+6.0j
2    3.0+8.0j
dtype: complex128

In [7]:
a=[True,False]
pd.Series(a)

0     True
1    False
dtype: bool

In [10]:
details={"names":["lohith","heamnth","krishna"],"marks":[70,60,75]}
pd.DataFrame(details)

     names  marks
0   lohith     70
1  heamnth     60
2  krishna     75

In [12]:
a={"names":["lohith","krishna","teja","hemanth"],"subjescts":["python","java","c","c++"],"marks":[70,80,60,75],"percentage":["80%","70%","65%","70%"]}
pd.DataFrame(a)

     names subjescts  marks percentage
0   lohith    python     70        80%
1  krishna      java     80        70%
2     teja         c     60        65%
3  hemanth       c++     75        70%

In [14]:
data=pd.read_csv("excel.csv")
data

   SNO      NAMES  MARKS BRANCH  CGPA
0    1     LOHTIH     77    CSE   7.5
1    2    HEMANTH     78    CSE   7.5
2    3    KRISHNA     79    CSE   7.5
3    4       TEJA     80    CSE   7.5
4    5      DURGA     81    EEE   7.5
5    6  VENKATESH     82    EEE   7.5
6    7       TAJU     83    EEE   7.9
7    8     KANTHU     84    EEE   7.9
8    9     REDDY      85    CSM   7.9
9   10        SAI     86    CSM   7.9

In [16]:
data=pd.read_csv("supermarket_large_dataset.csv")
data

,transaction_id,transaction_line_id,basket_id,customer_id,store_id,product_id,employee_id,supplier_id,customer_age,customer_gender,...,units_sold,sales_revenue,profit_per_unit,profit_margin,sales_rank,category_sales_rank,product_popularity,product_growth_rate,product_return_rate,product_stockout_rate
0,T00000001,TL00000001,B00044698,C00106069,S00000108,P00003814,E00000421,SUP00000007,60,Female,...,10,100.60,4.65,0.462,883,10,5.6,0.064,0.0580,0.0293
1,T00000002,TL00000002,B00013390,C00027234,S00000154,P00003904,E00000310,SUP00000035,54,Male,...,6,96.90,8.66,0.536,599,29,6.0,-0.025,0.0071,0.0028
2,T00000003,TL00000003,B00014357,C00019781,S00000136,P00000650,E00000344,SUP00000022,52,Male,...,6,132.18,7.90,0.359,389,49,5.2,-0.038,0.0029,0.0553
3,T00000004,TL00000004,B00046655,C00018191,S00000169,P00000966,E00000168,SUP00000005,40,Male,...,12,54.36,1.97,0.435,111,70,3.8,0.189,0.0146,0.0526
4,T00000005,TL00000005,B00046461,C00031493,S00000179,P00000584,E00000455,SUP00000014,44,Female,...,5,21.75,0.04,0.009,794,7,5.8,0.116,0.0479,0.1025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,T00119996,TL00119996,B00017350,C00040177,S00000119,P00002634,E00000259,SUP00000028,49,Female,...,8,70.32,3.30,0.375,32,58,6.3,0.129,0.0428,0.0796
119996,T00119997,TL00119997,B00024635,C00060645,S00000094,P00003906,E00000378,SUP00000042,39,Female,...,15,99.90,3.03,0.455,550,61,4.3,0.060,0.0424,0.0832
119997,T00119998,TL00119998,B00029265,C00021649,S00000175,P00003841,E00000212,SUP00000020,60,Female,...,16,112.16,2.15,0.307,13,32,4.3,-0.152,0.0000,0.0541
119998,T00119999,TL00119999,B00048485,C00017231,S00000164,P00000971,E00000276,SUP00000050,60,Male,...,20,85.40,1.41,0.330,506,98,4.0,-0.129,0.0269,0.0851
119999,T00120000,TL00120000,B00036356,C00052969,S00000059,P00001427,E00000109,SUP00000017,45,Male,...,4,9.56,1.08,0.452,444,48,4.7,-0.028,0.0523,0.0531

In [17]:
data.columns

Index(['transaction_id', 'transaction_line_id', 'basket_id', 'customer_id',
       'store_id', 'product_id', 'employee_id', 'supplier_id', 'customer_age',
       'customer_gender',
       ...
       'units_sold', 'sales_revenue', 'profit_per_unit', 'profit_margin',
       'sales_rank', 'category_sales_rank', 'product_popularity',
       'product_growth_rate', 'product_return_rate', 'product_stockout_rate'],
      dtype='str', length=323)

In [18]:
data.shape

(120000, 323)

In [19]:
data.info

<bound method DataFrame.info of        transaction_id transaction_line_id  basket_id customer_id   store_id  \
0           T00000001          TL00000001  B00044698   C00106069  S00000108
1           T00000002          TL00000002  B00013390   C00027234  S00000154
2           T00000003          TL00000003  B00014357   C00019781  S00000136
3           T00000004          TL00000004  B00046655   C00018191  S00000169
4           T00000005          TL00000005  B00046461   C00031493  S00000179
...               ...                 ...        ...         ...        ...
119995      T00119996          TL00119996  B00017350   C00040177  S00000119
119996      T00119997          TL00119997  B00024635   C00060645  S00000094
119997      T00119998          TL00119998  B00029265   C00021649  S00000175
119998      T00119999          TL00119999  B00048485   C00017231  S00000164
119999      T00120000          TL00120000  B00036356   C00052969  S00000059

       product_id employee_id  supplier_id  customer_age customer_gender  ...  \
0       P00003814   E00000421  SUP00000007            60          Female  ...
1       P00003904   E00000310  SUP00000035            54            Male  ...
2       P00000650   E00000344  SUP00000022            52            Male  ...
3       P00000966   E00000168  SUP00000005            40            Male  ...
4       P00000584   E00000455  SUP00000014            44          Female  ...
...           ...         ...          ...           ...             ...  ...
119995  P00002634   E00000259  SUP00000028            49          Female  ...
119996  P00003906   E00000378  SUP00000042            39          Female  ...
119997  P00003841   E00000212  SUP00000020            60          Female  ...
119998  P00000971   E00000276  SUP00000050            60            Male  ...
119999  P00001427   E00000109  SUP00000017            45            Male  ...

       units_sold sales_revenue profit_per_unit  profit_margin  sales_rank  \
0              10        100.60            4.65          0.462         883
1               6         96.90            8.66          0.536         599
2               6        132.18            7.90          0.359         389
3              12         54.36            1.97          0.435         111
4               5         21.75            0.04          0.009         794
...           ...           ...             ...            ...         ...
119995          8         70.32            3.30          0.375          32
119996         15         99.90            3.03          0.455         550
119997         16        112.16            2.15          0.307          13
119998         20         85.40            1.41          0.330         506
119999          4          9.56            1.08          0.452         444

        category_sales_rank product_popularity product_growth_rate  \
0                        10                5.6               0.064
1                        29                6.0              -0.025
2                        49                5.2              -0.038
3                        70                3.8               0.189
4                         7                5.8               0.116
...                     ...                ...                 ...
119995                   58                6.3               0.129
119996                   61                4.3               0.060
119997                   32                4.3              -0.152
119998                   98                4.0              -0.129
119999                   48                4.7              -0.028

       product_return_rate product_stockout_rate
0                   0.0580                0.0293
1                   0.0071                0.0028
2                   0.0029                0.0553
3                   0.0146                0.0526
4                   0.0479                0.1025
...                    ...                   ...
119995              0.0428                0.0796
119996              0.0424                0.0832
119997              0.0000                0.0541
119998              0.0269                0.0851
119999              0.0523                0.0531

[120000 rows x 323 columns]>